source 'https://rubygems.org'

gem 'activesupport'
gem 'allure-rspec'
gem 'allure-ruby-commons'
gem 'parallel_split_test'
gem 'parallel_tests'
gem 'rake'
gem 'reek'
gem 'rspec'
gem 'rubocop'
gem 'rubocop-rspec'
gem 'ruby_raider', '~> 0.7.0'
gem 'selenium-webdriver'
gem 'watir'
gem 'webdrivers'
